import Hello from "@/app/components/Hello";
import FetchProductsServerSide from "../components/FetchProductsServerSide";
export const metadata = {
  title: "Home | Next js",
  description: "Generated by create next app",
};
export default function Home() {
  console.log("what i am doiing? ");

  return (
    <>
      <h1 className="text-4xl">Welcome to next.js</h1>
      <Hello />
      <FetchProductsServerSide />
      <span className="mt-4 flex h-3"></span>
    </>
  );
}
